---
- name: Testing andrewrothstein.tfsec
  hosts: all
  tasks:
    - name: Installing andrewrothstein.tfsec
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Executing 'tfsec --version'
      ansible.builtin.command: /usr/local/bin/tfsec --version
      changed_when: false
      register: tfsec_test_output
    - name: tfsec --version
      ansible.builtin.debug:
        msg: '{{ tfsec_test_output.stdout }}'
